import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Babajka @ v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Babajka v3
        </h1>
      </main>
    </div>
  )
}
