name: lint & build

on: push

jobs:
  lint-build:
    runs-on: ubuntu-latest
    env:
      BABAJKA_GOOGLE_API_KEY: ${{ secrets.BABAJKA_GOOGLE_API_KEY }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: use node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: npm install
      - run: npm run lint
      - run: npm run build


